/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as CommerceRouteImport } from './routes/commerce'
import { Route as CmsRouteImport } from './routes/cms'
import { Route as ClientelingRouteImport } from './routes/clienteling'
import { Route as AtelierRouteImport } from './routes/atelier'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VipCareIndexRouteImport } from './routes/vip-care/index'
import { Route as VipCareTasksRouteImport } from './routes/vip-care/tasks'
import { Route as VipCareRelationshipsRouteImport } from './routes/vip-care/relationships'
import { Route as VipCarePerformanceRouteImport } from './routes/vip-care/performance'
import { Route as VipCareLookbooksRouteImport } from './routes/vip-care/lookbooks'
import { Route as VipCareInsightsRouteImport } from './routes/vip-care/insights'
import { Route as VipCareGiftsRouteImport } from './routes/vip-care/gifts'
import { Route as VipCareEventsRouteImport } from './routes/vip-care/events'
import { Route as VipCareAftercareRouteImport } from './routes/vip-care/aftercare'
import { Route as BackOfficeStaffRouteImport } from './routes/back-office/staff'
import { Route as BackOfficeSetupMfaRouteImport } from './routes/back-office/setup-mfa'
import { Route as BackOfficeAcceptInvitationRouteImport } from './routes/back-office/accept-invitation'
import { Route as VipCareClientsIndexRouteImport } from './routes/vip-care/clients/index'
import { Route as BackOfficeLoginIndexRouteImport } from './routes/back-office/login/index'
import { Route as VipCareClientsClientIdRouteImport } from './routes/vip-care/clients/$clientId'
import { Route as BackOfficeSettingsSecurityRouteImport } from './routes/back-office/settings/security'
import { Route as BackOfficeLoginMfaRouteImport } from './routes/back-office/login/mfa'

const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const CommerceRoute = CommerceRouteImport.update({
  id: '/commerce',
  path: '/commerce',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsRoute = CmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientelingRoute = ClientelingRouteImport.update({
  id: '/clienteling',
  path: '/clienteling',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierRoute = AtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VipCareIndexRoute = VipCareIndexRouteImport.update({
  id: '/vip-care/',
  path: '/vip-care/',
  getParentRoute: () => rootRouteImport,
} as any)
const VipCareTasksRoute = VipCareTasksRouteImport.update({
  id: '/vip-care/tasks',
  path: '/vip-care/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const VipCareRelationshipsRoute = VipCareRelationshipsRouteImport.update({
  id: '/vip-care/relationships',
  path: '/vip-care/relationships',
  getParentRoute: () => rootRouteImport,
} as any)
const VipCarePerformanceRoute = VipCarePerformanceRouteImport.update({
  id: '/vip-care/performance',
  path: '/vip-care/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const VipCareLookbooksRoute = VipCareLookbooksRouteImport.update({
  id: '/vip-care/lookbooks',
  path: '/vip-care/lookbooks',
  getParentRoute: () => rootRouteImport,
} as any)
const VipCareInsightsRoute = VipCareInsightsRouteImport.update({
  id: '/vip-care/insights',
  path: '/vip-care/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const VipCareGiftsRoute = VipCareGiftsRouteImport.update({
  id: '/vip-care/gifts',
  path: '/vip-care/gifts',
  getParentRoute: () => rootRouteImport,
} as any)
const VipCareEventsRoute = VipCareEventsRouteImport.update({
  id: '/vip-care/events',
  path: '/vip-care/events',
  getParentRoute: () => rootRouteImport,
} as any)
const VipCareAftercareRoute = VipCareAftercareRouteImport.update({
  id: '/vip-care/aftercare',
  path: '/vip-care/aftercare',
  getParentRoute: () => rootRouteImport,
} as any)
const BackOfficeStaffRoute = BackOfficeStaffRouteImport.update({
  id: '/back-office/staff',
  path: '/back-office/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const BackOfficeSetupMfaRoute = BackOfficeSetupMfaRouteImport.update({
  id: '/back-office/setup-mfa',
  path: '/back-office/setup-mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const BackOfficeAcceptInvitationRoute =
  BackOfficeAcceptInvitationRouteImport.update({
    id: '/back-office/accept-invitation',
    path: '/back-office/accept-invitation',
    getParentRoute: () => rootRouteImport,
  } as any)
const VipCareClientsIndexRoute = VipCareClientsIndexRouteImport.update({
  id: '/vip-care/clients/',
  path: '/vip-care/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackOfficeLoginIndexRoute = BackOfficeLoginIndexRouteImport.update({
  id: '/back-office/login/',
  path: '/back-office/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const VipCareClientsClientIdRoute = VipCareClientsClientIdRouteImport.update({
  id: '/vip-care/clients/$clientId',
  path: '/vip-care/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const BackOfficeSettingsSecurityRoute =
  BackOfficeSettingsSecurityRouteImport.update({
    id: '/back-office/settings/security',
    path: '/back-office/settings/security',
    getParentRoute: () => rootRouteImport,
  } as any)
const BackOfficeLoginMfaRoute = BackOfficeLoginMfaRouteImport.update({
  id: '/back-office/login/mfa',
  path: '/back-office/login/mfa',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/atelier': typeof AtelierRoute
  '/clienteling': typeof ClientelingRoute
  '/cms': typeof CmsRoute
  '/commerce': typeof CommerceRoute
  '/ledger': typeof LedgerRoute
  '/security': typeof SecurityRoute
  '/vault': typeof VaultRoute
  '/back-office/accept-invitation': typeof BackOfficeAcceptInvitationRoute
  '/back-office/setup-mfa': typeof BackOfficeSetupMfaRoute
  '/back-office/staff': typeof BackOfficeStaffRoute
  '/vip-care/aftercare': typeof VipCareAftercareRoute
  '/vip-care/events': typeof VipCareEventsRoute
  '/vip-care/gifts': typeof VipCareGiftsRoute
  '/vip-care/insights': typeof VipCareInsightsRoute
  '/vip-care/lookbooks': typeof VipCareLookbooksRoute
  '/vip-care/performance': typeof VipCarePerformanceRoute
  '/vip-care/relationships': typeof VipCareRelationshipsRoute
  '/vip-care/tasks': typeof VipCareTasksRoute
  '/vip-care/': typeof VipCareIndexRoute
  '/back-office/login/mfa': typeof BackOfficeLoginMfaRoute
  '/back-office/settings/security': typeof BackOfficeSettingsSecurityRoute
  '/vip-care/clients/$clientId': typeof VipCareClientsClientIdRoute
  '/back-office/login/': typeof BackOfficeLoginIndexRoute
  '/vip-care/clients/': typeof VipCareClientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/atelier': typeof AtelierRoute
  '/clienteling': typeof ClientelingRoute
  '/cms': typeof CmsRoute
  '/commerce': typeof CommerceRoute
  '/ledger': typeof LedgerRoute
  '/security': typeof SecurityRoute
  '/vault': typeof VaultRoute
  '/back-office/accept-invitation': typeof BackOfficeAcceptInvitationRoute
  '/back-office/setup-mfa': typeof BackOfficeSetupMfaRoute
  '/back-office/staff': typeof BackOfficeStaffRoute
  '/vip-care/aftercare': typeof VipCareAftercareRoute
  '/vip-care/events': typeof VipCareEventsRoute
  '/vip-care/gifts': typeof VipCareGiftsRoute
  '/vip-care/insights': typeof VipCareInsightsRoute
  '/vip-care/lookbooks': typeof VipCareLookbooksRoute
  '/vip-care/performance': typeof VipCarePerformanceRoute
  '/vip-care/relationships': typeof VipCareRelationshipsRoute
  '/vip-care/tasks': typeof VipCareTasksRoute
  '/vip-care': typeof VipCareIndexRoute
  '/back-office/login/mfa': typeof BackOfficeLoginMfaRoute
  '/back-office/settings/security': typeof BackOfficeSettingsSecurityRoute
  '/vip-care/clients/$clientId': typeof VipCareClientsClientIdRoute
  '/back-office/login': typeof BackOfficeLoginIndexRoute
  '/vip-care/clients': typeof VipCareClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/atelier': typeof AtelierRoute
  '/clienteling': typeof ClientelingRoute
  '/cms': typeof CmsRoute
  '/commerce': typeof CommerceRoute
  '/ledger': typeof LedgerRoute
  '/security': typeof SecurityRoute
  '/vault': typeof VaultRoute
  '/back-office/accept-invitation': typeof BackOfficeAcceptInvitationRoute
  '/back-office/setup-mfa': typeof BackOfficeSetupMfaRoute
  '/back-office/staff': typeof BackOfficeStaffRoute
  '/vip-care/aftercare': typeof VipCareAftercareRoute
  '/vip-care/events': typeof VipCareEventsRoute
  '/vip-care/gifts': typeof VipCareGiftsRoute
  '/vip-care/insights': typeof VipCareInsightsRoute
  '/vip-care/lookbooks': typeof VipCareLookbooksRoute
  '/vip-care/performance': typeof VipCarePerformanceRoute
  '/vip-care/relationships': typeof VipCareRelationshipsRoute
  '/vip-care/tasks': typeof VipCareTasksRoute
  '/vip-care/': typeof VipCareIndexRoute
  '/back-office/login/mfa': typeof BackOfficeLoginMfaRoute
  '/back-office/settings/security': typeof BackOfficeSettingsSecurityRoute
  '/vip-care/clients/$clientId': typeof VipCareClientsClientIdRoute
  '/back-office/login/': typeof BackOfficeLoginIndexRoute
  '/vip-care/clients/': typeof VipCareClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/atelier'
    | '/clienteling'
    | '/cms'
    | '/commerce'
    | '/ledger'
    | '/security'
    | '/vault'
    | '/back-office/accept-invitation'
    | '/back-office/setup-mfa'
    | '/back-office/staff'
    | '/vip-care/aftercare'
    | '/vip-care/events'
    | '/vip-care/gifts'
    | '/vip-care/insights'
    | '/vip-care/lookbooks'
    | '/vip-care/performance'
    | '/vip-care/relationships'
    | '/vip-care/tasks'
    | '/vip-care/'
    | '/back-office/login/mfa'
    | '/back-office/settings/security'
    | '/vip-care/clients/$clientId'
    | '/back-office/login/'
    | '/vip-care/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/atelier'
    | '/clienteling'
    | '/cms'
    | '/commerce'
    | '/ledger'
    | '/security'
    | '/vault'
    | '/back-office/accept-invitation'
    | '/back-office/setup-mfa'
    | '/back-office/staff'
    | '/vip-care/aftercare'
    | '/vip-care/events'
    | '/vip-care/gifts'
    | '/vip-care/insights'
    | '/vip-care/lookbooks'
    | '/vip-care/performance'
    | '/vip-care/relationships'
    | '/vip-care/tasks'
    | '/vip-care'
    | '/back-office/login/mfa'
    | '/back-office/settings/security'
    | '/vip-care/clients/$clientId'
    | '/back-office/login'
    | '/vip-care/clients'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/atelier'
    | '/clienteling'
    | '/cms'
    | '/commerce'
    | '/ledger'
    | '/security'
    | '/vault'
    | '/back-office/accept-invitation'
    | '/back-office/setup-mfa'
    | '/back-office/staff'
    | '/vip-care/aftercare'
    | '/vip-care/events'
    | '/vip-care/gifts'
    | '/vip-care/insights'
    | '/vip-care/lookbooks'
    | '/vip-care/performance'
    | '/vip-care/relationships'
    | '/vip-care/tasks'
    | '/vip-care/'
    | '/back-office/login/mfa'
    | '/back-office/settings/security'
    | '/vip-care/clients/$clientId'
    | '/back-office/login/'
    | '/vip-care/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  AtelierRoute: typeof AtelierRoute
  ClientelingRoute: typeof ClientelingRoute
  CmsRoute: typeof CmsRoute
  CommerceRoute: typeof CommerceRoute
  LedgerRoute: typeof LedgerRoute
  SecurityRoute: typeof SecurityRoute
  VaultRoute: typeof VaultRoute
  BackOfficeAcceptInvitationRoute: typeof BackOfficeAcceptInvitationRoute
  BackOfficeSetupMfaRoute: typeof BackOfficeSetupMfaRoute
  BackOfficeStaffRoute: typeof BackOfficeStaffRoute
  VipCareAftercareRoute: typeof VipCareAftercareRoute
  VipCareEventsRoute: typeof VipCareEventsRoute
  VipCareGiftsRoute: typeof VipCareGiftsRoute
  VipCareInsightsRoute: typeof VipCareInsightsRoute
  VipCareLookbooksRoute: typeof VipCareLookbooksRoute
  VipCarePerformanceRoute: typeof VipCarePerformanceRoute
  VipCareRelationshipsRoute: typeof VipCareRelationshipsRoute
  VipCareTasksRoute: typeof VipCareTasksRoute
  VipCareIndexRoute: typeof VipCareIndexRoute
  BackOfficeLoginMfaRoute: typeof BackOfficeLoginMfaRoute
  BackOfficeSettingsSecurityRoute: typeof BackOfficeSettingsSecurityRoute
  VipCareClientsClientIdRoute: typeof VipCareClientsClientIdRoute
  BackOfficeLoginIndexRoute: typeof BackOfficeLoginIndexRoute
  VipCareClientsIndexRoute: typeof VipCareClientsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commerce': {
      id: '/commerce'
      path: '/commerce'
      fullPath: '/commerce'
      preLoaderRoute: typeof CommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms': {
      id: '/cms'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof CmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clienteling': {
      id: '/clienteling'
      path: '/clienteling'
      fullPath: '/clienteling'
      preLoaderRoute: typeof ClientelingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier': {
      id: '/atelier'
      path: '/atelier'
      fullPath: '/atelier'
      preLoaderRoute: typeof AtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip-care/': {
      id: '/vip-care/'
      path: '/vip-care'
      fullPath: '/vip-care/'
      preLoaderRoute: typeof VipCareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip-care/tasks': {
      id: '/vip-care/tasks'
      path: '/vip-care/tasks'
      fullPath: '/vip-care/tasks'
      preLoaderRoute: typeof VipCareTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip-care/relationships': {
      id: '/vip-care/relationships'
      path: '/vip-care/relationships'
      fullPath: '/vip-care/relationships'
      preLoaderRoute: typeof VipCareRelationshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip-care/performance': {
      id: '/vip-care/performance'
      path: '/vip-care/performance'
      fullPath: '/vip-care/performance'
      preLoaderRoute: typeof VipCarePerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip-care/lookbooks': {
      id: '/vip-care/lookbooks'
      path: '/vip-care/lookbooks'
      fullPath: '/vip-care/lookbooks'
      preLoaderRoute: typeof VipCareLookbooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip-care/insights': {
      id: '/vip-care/insights'
      path: '/vip-care/insights'
      fullPath: '/vip-care/insights'
      preLoaderRoute: typeof VipCareInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip-care/gifts': {
      id: '/vip-care/gifts'
      path: '/vip-care/gifts'
      fullPath: '/vip-care/gifts'
      preLoaderRoute: typeof VipCareGiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip-care/events': {
      id: '/vip-care/events'
      path: '/vip-care/events'
      fullPath: '/vip-care/events'
      preLoaderRoute: typeof VipCareEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip-care/aftercare': {
      id: '/vip-care/aftercare'
      path: '/vip-care/aftercare'
      fullPath: '/vip-care/aftercare'
      preLoaderRoute: typeof VipCareAftercareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/back-office/staff': {
      id: '/back-office/staff'
      path: '/back-office/staff'
      fullPath: '/back-office/staff'
      preLoaderRoute: typeof BackOfficeStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/back-office/setup-mfa': {
      id: '/back-office/setup-mfa'
      path: '/back-office/setup-mfa'
      fullPath: '/back-office/setup-mfa'
      preLoaderRoute: typeof BackOfficeSetupMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/back-office/accept-invitation': {
      id: '/back-office/accept-invitation'
      path: '/back-office/accept-invitation'
      fullPath: '/back-office/accept-invitation'
      preLoaderRoute: typeof BackOfficeAcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip-care/clients/': {
      id: '/vip-care/clients/'
      path: '/vip-care/clients'
      fullPath: '/vip-care/clients/'
      preLoaderRoute: typeof VipCareClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/back-office/login/': {
      id: '/back-office/login/'
      path: '/back-office/login'
      fullPath: '/back-office/login/'
      preLoaderRoute: typeof BackOfficeLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip-care/clients/$clientId': {
      id: '/vip-care/clients/$clientId'
      path: '/vip-care/clients/$clientId'
      fullPath: '/vip-care/clients/$clientId'
      preLoaderRoute: typeof VipCareClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/back-office/settings/security': {
      id: '/back-office/settings/security'
      path: '/back-office/settings/security'
      fullPath: '/back-office/settings/security'
      preLoaderRoute: typeof BackOfficeSettingsSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/back-office/login/mfa': {
      id: '/back-office/login/mfa'
      path: '/back-office/login/mfa'
      fullPath: '/back-office/login/mfa'
      preLoaderRoute: typeof BackOfficeLoginMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  AtelierRoute: AtelierRoute,
  ClientelingRoute: ClientelingRoute,
  CmsRoute: CmsRoute,
  CommerceRoute: CommerceRoute,
  LedgerRoute: LedgerRoute,
  SecurityRoute: SecurityRoute,
  VaultRoute: VaultRoute,
  BackOfficeAcceptInvitationRoute: BackOfficeAcceptInvitationRoute,
  BackOfficeSetupMfaRoute: BackOfficeSetupMfaRoute,
  BackOfficeStaffRoute: BackOfficeStaffRoute,
  VipCareAftercareRoute: VipCareAftercareRoute,
  VipCareEventsRoute: VipCareEventsRoute,
  VipCareGiftsRoute: VipCareGiftsRoute,
  VipCareInsightsRoute: VipCareInsightsRoute,
  VipCareLookbooksRoute: VipCareLookbooksRoute,
  VipCarePerformanceRoute: VipCarePerformanceRoute,
  VipCareRelationshipsRoute: VipCareRelationshipsRoute,
  VipCareTasksRoute: VipCareTasksRoute,
  VipCareIndexRoute: VipCareIndexRoute,
  BackOfficeLoginMfaRoute: BackOfficeLoginMfaRoute,
  BackOfficeSettingsSecurityRoute: BackOfficeSettingsSecurityRoute,
  VipCareClientsClientIdRoute: VipCareClientsClientIdRoute,
  BackOfficeLoginIndexRoute: BackOfficeLoginIndexRoute,
  VipCareClientsIndexRoute: VipCareClientsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
